language: node_js
node_js:
- 7
- 6
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - ryanbas21@gmail.com
    on_success: never
    on_failure: always
env:
  global:
  - secure: tDTWeof0j8WqEks2030Q7Ayx8COa3hMylXcKEMw4LyEzFSAfdbrdv30h73dPQWQrETzRuwTZr9gLRxCJJZRYH6YR2BQcozhD6z8pguJD0G5w5v5dfH0OLl/Z3zuUWUvBzrphgEdf9pSAkXdiQSUD1LJteelNzu5X9sFndHTDLYA8b9lv1B1EsJG3n9AJVYHtswAadP/apWkw4GRyV2VBqkdyy/UgfNB2vag04+ANhUIb7WUHm+ZyXAJWmReUD//EQ/275QxSL0NgwC6c39iqjJZd2L0FJaD+0+v2ALcaRG7vXmn0IiF4NCb0LdWsDY38isiIt/WXdkpnHmlQVwyJE1bvm4X0abmNprfLyE1kPRx2xUTI0YGKdvgFcs2GzuxW9qZJE3j4NmBwe6mC5g9jpz6hYUUkjHcflK45c49ZJQTkUbvhyFUodTIBqK+Ff57mELguEdEdASFCz6d97rlyuiK5eWUbM1GbH/IjsQRWmuJ6LYSJuAUkI4jZ+qTQYCyvANKVKEPeO3CyEHwX8peKCfneaq89oyKxPODJAPWjZcMdrmXrBm54C26Vu8dVSePHVAvsjh4eBvy+BLPNHUD61TcAETKze9JYPWKia8Re+vl3ArjStljJbmPKskh/Sgh6DLoFRxoNWBCT0QCsDzKCATS6w2WSsidloIw1DCD8D4o=
  - secure: JbeMCR4qTKQk91trnAk6Wpu0RPVGixCkv8h7Q53PDBbomL5nuFG/IDw/d9g5EuXIlBWXNcfpFgAH6ZrSi6pM+mds4YM5N8+7yr5BtWer5VFOE1Pjg7N4y/cin/gLMnxL2LSURp5j1j5/ytWfKucKlO4zuMZ3Uc0hZbCXYtMzR5hS8KVU25M3kwTzwLO53ZjOy/+/XtBOmErFdGXRwEvi+ofvalRX2b+16w84oNCd/EiFg1qaKLSW0pMe4vB1C6yxZ/irjosECQPK4Gttk84K5Q0UleGFiU4AXzCM1YAcKTKgb+aaZDDr/otRXULIHKL4iNmkod2tUdGfpCui5qJkrA60P7Vz2DAebwBoQ5PzohzfOpVEzNEFdZgm2ZSwMxpswvM6+ajfRdCO1wVmJPRIF7x5o++YR0YkApo96a4/yj2e8WIUZ0XL2HXHvFihuE6SlD0+Zr8KUj9+qDWcXOiWzEpNhOEprL7RGnBGzg8bLZU/CNEOPLj37oiYtKzfKIk+Nb7FSYaWpUx5JeV42Vcy6GCvpb3oIyILIVZgxcyU5TOR6mczOl8+EmmVccw1MLKdBmPNoZkGaWcDaibZ6/jpBBGc1VBJGeVviB8WZSSY2Y3PbZOUVtSZLOfo7uYt/0bz+KuZSK2Yj1vAZGHFjbWgP1pas/azVlCZKAQF/b9eG4A=
  - secure: bL7Bl0Ladg3Wif0DPsLtPcPz2hons6qwnA7GuFIpZeNhMDAyGFzW4NeGDLAqzwx3P+k1CjLPD5MbST8Tebwq9ww8pGS62duzOjgtEK+CwTVr0sbvR010kHVytYafnNIJprthlE47tjRQV4Y7SG7laBg5lSZw9qAoygTGJXIqDghlxK1A7iKz2n8uwdCpmtohnSs363akaNyTKFMe+bYKx29+OgD9XlNnr+4TbW+F4t2h3AjAIxlwnItzDgHiSK4qDnPhTooM9e8IAN3Q9eG34y9XxEA53EsWPnNf1QD66WL0WuUuBjtn+45E7deTytCTFliW9Ii+5qskQgQuSHzgUyQbvwxn3DL6lHdd+s+SSFgxMxtLPNzwnQk2+Jqe+vaVmKvBEf1WkodkF2MG24QtBaauLFo2+87mlcFgOZn7AJ0IKinwcGKvwahBgWq282ShI4j5yp+Df+71Sk4NKTiHUMxqTZuTVG4qeq6lH08YVmU4IzqOhmeDXrv3XgqB0yWu8ogG6PL2doQYh70Zp9lj8UaWXG7tZPOGSoHuvB9Jbytml2M50/wja68pOVWe94xfmWQ5jVZZ+lNYlQ3iiRpUbfNOod7wEJJx0yc8fVA1Wsonne6E3KNx4Kix8J/00GIm8S/UvTmEqoNoN+2gM+gvOBOVUx35E+kjxqzQB0JrRDg=
after_success: ./merge.sh $USERNAME $PASSWORD
